language: node_js
node_js:
  - "10"
dist: trusty
addons:
  chrome: stable
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
before_script:
  - npm install -g @angular/cli
script:
  - npm run lint:lib
  - npm run test-ci
  - codecov
  - npm run build:lib
before_deploy:
  - npm run copy:readme
  - npm run copy:changelog
  - npm run copy:license
  - cd dist/simple-loader-lib
deploy:
  provider: npm
  email: sathishcharykotha@gmail.com
  skip_cleanup: true
  api_token: $NPM_TOKEN
  tag: latest
  edge: true
  on:
    tags: true
    repo: simple-loader-lib
